import {
  readFileSync,
  writeFileSync,
  mkdirSync,
  existsSync,
  readdirSync,
} from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import {
  buildOverviewSection,
  buildIndexPage,
  buildPagesList,
} from "../../scripts/lib/index-builder.js";

// ─── Environment ─────────────────────────────────────────────────────

const dashbuildDir = process.env.DASHBUILD_DIR;

if (!dashbuildDir) {
  console.error(
    "::error::DASHBUILD_DIR is not set. Did you run dashbuild/setup first?",
  );
  process.exit(1);
}

// ─── Load configuration ──────────────────────────────────────────────

const configPath = join(dashbuildDir, "dashbuild-config.json");
const modulesPath = join(dashbuildDir, "modules.json");

let siteConfig;
try {
  siteConfig = JSON.parse(readFileSync(configPath, "utf-8"));
} catch {
  siteConfig = { title: "Dashbuild Report", theme: "dashboard" };
}

let registeredModules;
try {
  registeredModules = JSON.parse(readFileSync(modulesPath, "utf-8"));
} catch {
  registeredModules = [];
}

console.log(
  `Assembling site: "${siteConfig.title}" with ${registeredModules.length} module(s)`,
);

// ─── Group modules by section ────────────────────────────────────────

const sidebarPages = buildPagesList(
  registeredModules.map((m) => ({
    name: m.name,
    path: m.path,
    section: m.section || "Reports",
  })),
);

// ─── Generate observablehq.config.js ─────────────────────────────────

// Per-page style front matter in each module's page.md handles theme loading.
const frameworkConfig = {
  title: siteConfig.title,
  root: "src",
  theme: siteConfig.theme || "dashboard",
  pager: false,
  head: `<link rel="stylesheet" href="./components/dashbuild-base.css"><link rel="stylesheet" href="./components/dashbuild-components.css"><style>observablehq-loading{display:none!important}.observablehq--block:empty{display:none!important}#observablehq-footer{opacity:0;animation:dashFadeIn 150ms ease-out forwards;animation-delay:calc(6 * 30ms)}</style>`,
  pages: sidebarPages,
};

const configFileContent = `// Auto-generated by dashbuild/compile — do not edit manually
export default ${JSON.stringify(frameworkConfig, null, 2)};
`;

writeFileSync(
  join(dashbuildDir, "observablehq.config.js"),
  configFileContent,
  "utf-8",
);
console.log("Generated observablehq.config.js");

// ─── Collect module API data ────────────────────────────────────────

const showOverview = process.env.DASHBUILD_SHOW_OVERVIEW !== "false";
const moduleApiDir = join(dashbuildDir, "module-api");
const overviews = [];

if (existsSync(moduleApiDir)) {
  const apiDirs = readdirSync(moduleApiDir, { withFileTypes: true }).filter(
    (d) => d.isDirectory(),
  );

  for (const dir of apiDirs) {
    const overviewPath = join(moduleApiDir, dir.name, "overview.json");
    if (existsSync(overviewPath)) {
      try {
        const overview = JSON.parse(readFileSync(overviewPath, "utf-8"));
        overviews.push(overview);
      } catch (err) {
        console.warn(
          `Warning: Could not parse ${overviewPath}: ${err.message}`,
        );
      }
    }
  }
}

console.log(
  `Collected ${overviews.length} module overview(s)${
    showOverview ? "" : " (display disabled)"
  }`,
);

// ─── Generate index.md ───────────────────────────────────────────────

const overviewSection = showOverview ? buildOverviewSection(overviews) : "";

const footer = `
---

\`\`\`js
const generatedDate = new Date().toLocaleDateString("en-US", {year: "numeric", month: "long", day: "numeric", hour: "2-digit", minute: "2-digit"});
\`\`\`

<div class="dash-section" style="--si:2">
<div class="note">
  Generated on <code>\${generatedDate}</code> with ${registeredModules.length} module(s).
</div>
</div>
`;

const indexContent = buildIndexPage({
  title: "Dashboard",
  subtitle: siteConfig.subtitle || "Development Report",
  overviewSection,
  footer,
});

writeFileSync(join(dashbuildDir, "src", "index.md"), indexContent, "utf-8");
console.log("Generated src/index.md");

console.log("Site assembly complete. Ready to build.");
