name: "Dashbuild __MODULE_TITLE__"
description: "TODO: describe what this module does"

inputs:
  example-input:
    description: "An example input parameter"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Generate report page
      shell: bash
      run: node "${DASHBUILD_ROOT}/scripts/lib/generate-page.js" "${{ github.action_path }}"

    - name: Generate overview
      shell: bash
      run: node "${{ github.action_path }}/scripts/generate-overview.js"

    - name: Register module
      shell: bash
      run: node "${DASHBUILD_ROOT}/scripts/lib/register-module.js" "${{ github.action_path }}"
